name: Deploy RDS Infrastructure (Terraform)

on:
  workflow_dispatch:

jobs:
  terraform-rds:
    name: Provisionar Banco de Dados RDS (Terraform)
    runs-on: ubuntu-latest
    environment: AWS_ACADEMY
    
    concurrency:
      group: deploy-rds
      cancel-in-progress: false

    steps:
      - name: Checkout do código
        uses: actions/checkout@v7

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false

      - name: Garantir Bucket S3 do Terraform State
        run: |
          aws s3api head-bucket --bucket "ofisy-tfstate-${{ secrets.AWS_ACCOUNT_ID }}" 2>/dev/null || \
          aws s3api create-bucket --bucket "ofisy-tfstate-${{ secrets.AWS_ACCOUNT_ID }}" --region us-east-1 || echo "Bucket já existente ou criado."

      - name: Configurar Arquivos de Variáveis
        env:
          DB_PASS: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "::add-mask::$DB_PASS"
          cd infra
          echo 'account_id = "${{ secrets.AWS_ACCOUNT_ID }}"' > terraform.tfvars
          echo "db_password = \"$DB_PASS\"" >> terraform.tfvars
          
          echo 'bucket = "ofisy-tfstate-${{ secrets.AWS_ACCOUNT_ID }}"' > backend.hcl
          echo 'key    = "rds/terraform.tfstate"' >> backend.hcl
          echo 'region = "us-east-1"' >> backend.hcl

      - name: Terraform Init
        run: |
          cd infra
          terraform init -backend-config=backend.hcl

      - name: Terraform Plan
        run: |
          cd infra
          terraform plan -no-color > plan.txt
          cat plan.txt
          echo "### Planejamento de Infraestrutura do RDS" >> $GITHUB_STEP_SUMMARY
          echo '```terraform' >> $GITHUB_STEP_SUMMARY
          cat plan.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Terraform Apply
        run: |
          cd infra
          terraform apply -auto-approve
          
          RDS_ENDPOINT=$(terraform output -raw rds_address)
          echo "### RDS Provisionado com Sucesso" >> $GITHUB_STEP_SUMMARY
          echo "- Endpoint: $RDS_ENDPOINT" >> $GITHUB_STEP_SUMMARY
